package com.journaldev.spring.model;
// Generated Aug 18, 2016 8:39:24 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Title generated by hbm2java
 */
@Entity
@Table(name = "title", catalog = "ReadersLog")
public class Title implements java.io.Serializable {

	private Integer id;
	private String name;
	private String author;
	private Integer styleId;

	public Title() {
	}

	public Title(String name, String author, Integer styleId) {
		this.name = name;
		this.author = author;
		this.styleId = styleId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "author")
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "styleId")
	public Integer getStyleId() {
		return this.styleId;
	}

	public void setStyleId(Integer styleId) {
		this.styleId = styleId;
	}

}
